### ISSUE TITLE
Periodically age unused card templates

### ISSUE THREAD

**Issue by asilano** [asilano/multidraft#8]
And configure vacuuming on OpenShift

**Comment by asilano** [comment]
While I'm mucking about in OpenShift's internals, also add a post_deploy action-hook to run rake db:seed

**Comment by tvvocold** [comment]
Hi there, 
How to deploy it in Openshift? Is there a demo online?

**Comment by asilano** [comment]
Hi,

Thanks for your interest. This isn't really meant to be a publically-deployable project; it's something I'm working on in my spare time, and will probably take a long time to finish!

The current state is live at http://app-multidraft.rhcloud.com if you want to take a look. If you're interested in custom magic sets generally, then I'd point you to my friend's site (which should eventually link in to multidraft) - www.magicmultiverse.net.
